build: 
	g++    client.cpp     ../common/common.cpp   -o -std=c++17 -lstdc++fs client && \
	g++ ../server/server.cpp     ../login/login.cpp    ../common/common.cpp -o -std=c++17 -lstdc++fs ../server/server 
