build: 
	g++ server.cpp     ../login/login.cpp    ../common/common.cpp -o -std=c++17server -lstdc++fs && \
	g++    ../client/client.cpp     ../common/common.cpp   -o -std=c++17 -lstdc++fs  ../client/client 
